# Site Settings
baseurl: ""
url : "https://jiyeongyun.github.io"

# Blog Settings
theme_settings :
  title : ê°œ ë°œìêµ­ ğŸ¾
  favicon : assets/profile.png

  # Profile Settings
  profile :
    image : assets/profile.png
    username : ìœ¤ì§€ì˜(YUN, JIYEONG)
    description : ê°œë°œ ìêµ­ ğŸ¾
    experience :
      - start : 2017-03-01
        end : 2019-06-14
        experience : 'ì‹œì„ ', ì†Œì™¸ëœ ì´ì›ƒë“¤ì„ ìœ„í•œ IT ì†”ë£¨ì…˜ í•™íšŒ
        description : í•œë™ëŒ€í•™êµ ì „ì‚° í•™íšŒ 
      - start : 2016-09-01
        end : 2017-06-16
        experience : ì²œí’í•´ì„¸
        description : í•œë™ëŒ€í•™êµ íƒœê¶Œë„ ë™ì•„ë¦¬ 
      - start : 2016-02-22
        end : On Going
        experience : Handong Global University
        description : ì „ì‚°ì „ìê³µí•™ë¶€ ì»´í“¨í„°ê³µí•™ì‹¬í™” ì „ê³µ

    skills : 
      - skill : Java
        value : 90  # Percent value
        
  # Icons
  icons :
    email:  yoonjy1106
    linkedin:  # Full URL 
    github: jiyeongyun
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: yeong.jpg

  # Disqus
  disqus_shortname : jiyeong

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
