# Site Settings
baseurl: ""
url : "https://jiyeongyun.github.io"

# Blog Settings
theme_settings :
  title : '개발'자국  
  favicon : assets/favicon.png

  # Profile Settings
  profile :
    image : assets/img/profile.png
    username : 윤지영(YUN, JIYEONG)
    description : '개발'자국
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : Java
        value : 90  # Percent value
        
  # Icons
  icons :
    email:  yoonjy1106@gmail.com
    linkedin:  # Full URL 
    github: jiyeongyun
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: yeong.jpg

  # Disqus
  disqus_shortname : jiyeong

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
