# Site Settings
baseurl: ""
url : "https://jiyeongyun.github.io"

# Blog Settings
theme_settings :
  title : ê°œ ë°œìêµ­ ğŸ¾
  favicon : assets/profile.png

  # Profile Settings
  profile :
    image : assets/profile.png
    username : ìœ¤ì§€ì˜(YUN, JIYEONG)
    description : ê°œë°œ ìêµ­ ğŸ¾
    experience :
      - start : 2016-07-01
        end : 2016-08-31
        experience : company name, title
    skills : 
      - skill : Java
        value : 90  # Percent value
        
  # Icons
  icons :
    email:  yoonjy1106@gmail.com
    linkedin:  # Full URL 
    github: jiyeongyun
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: yeong.jpg

  # Disqus
  disqus_shortname : jiyeong

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
